# Generated by Django 4.0.6 on 2022-10-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_txt1', models.TextField()),
                ('image1', models.ImageField(upload_to='media/media')),
                ('d_txt2', models.TextField()),
                ('image2', models.ImageField(upload_to='media/media')),
            ],
        ),
    ]
