# Generated by Django 4.0.6 on 2022-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_lab2_delete_about_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_service_h', models.CharField(max_length=150)),
                ('about_service_t1', models.TextField()),
                ('about_service_t2', models.TextField()),
                ('about_service_t3', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About_service',
        ),
    ]
