# Generated by Django 4.0.6 on 2022-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blogs_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blogs_Txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blogs_TxtH',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
