# Generated by Django 4.0.6 on 2022-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogs_slug_alter_blogs_blogs_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs_TxtH', models.CharField(blank=True, max_length=150, null=True)),
                ('blogs_Txt', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('blogs_Image', models.ImageField(blank=True, null=True, upload_to='media/media')),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
