# Generated by Django 4.0.6 on 2022-10-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_h', models.CharField(max_length=150)),
                ('about_t', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_service_h', models.CharField(max_length=150)),
                ('about_service_t', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About_service_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_txt1', models.TextField()),
                ('image1', models.ImageField(upload_to='media/media')),
                ('d_txt2', models.TextField()),
                ('image2', models.ImageField(upload_to='media/media')),
            ],
        ),
        migrations.CreateModel(
            name='Img_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/media')),
            ],
        ),
        migrations.CreateModel(
            name='Text_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Txt_foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_foot', models.CharField(max_length=150)),
                ('d_txt1', models.TextField()),
                ('d_txt2', models.TextField()),
                ('d_txt3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Txt_wwr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_head', models.CharField(max_length=200)),
                ('d_txt', models.TextField()),
            ],
        ),
    ]
